package serversockets;

import Connection.Server;
import Connection.ejemploObserver;

public class ServerSockets {

    public static void main(String[] args) {

        Server server = new Server(8080);
        
        try {
            server.Init();
            
            // To send data to clients:
            // server.sendToClients(String json)
            // server.sendToClients(String json, String ID)
            // server.sendToClients(String json, String[] IDs)
            // (ID: Is the ID of each clientConnection that is auto-generated by the Server when the client is connected succesfuly)
            
            // Observer for manage the sockets messages
            ejemploObserver obs = new ejemploObserver();
            server.addObserver(obs);
            
            
            
            System.out.println("Server online");
        } catch (Exception e) {
            System.out.println("Error: "+e.getMessage());
        }

    }

}
